# fly.toml app configuration file generated for metaverse-mmo-server on 2026-06-10T16:05:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'metaverse-mmo-server'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 25000

  [[services.ports]]
    port = 25000

[[services]]
  protocol = 'udp'
  internal_port = 25001

  [[services.ports]]
    port = 25001

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
